/**:
  ros__parameters:
    execute: true
    # Total planning attempts
    max_solutions: 20

    # Planning group and link names
    arm_group_name: "arm"
    eef_name: "end_effector"
    hand_group_name: "gripper"
    hand_frame: "arm_end_effector_link"

    # Poses
    hand_open_pose: "open"
    hand_close_pose: "close"
    arm_home_pose: "ready"

    # Scene frames
    world_frame: "map"
    table_reference_frame: "base_link"
    object_reference_frame: "arm_base_link"
    surface_link: "table"

    # Collision object for picking
    # CYLINDER object specifications
    object_name: "object"
    object_dimensions: [0.26, 0.02] # [height, radius]
    object_pose: [0.0, 0.4, 0.1, 0.0, 0.0, 0.0]

    # Table model
    spawn_table: true
    table_name: "table"
    table_dimensions: [0.80, 0.90, 0.2]  # [length, width, height]
    table_pose: [-0.33, -1.0, -0.14, 0.0, 0.0, 0.0]

    # Gripper grasp frame transform [x,y,z,r,p,y]
    grasp_frame_transform: [0.0, 0.0, 0.1, -1.571, 0.0, 1.571] #[0.0, 0.0, 0.1, 1.571, 0.785, 1.571]

    # Place pose [x,y,z,r,p,y]
    place_pose: [0.6, -0.15, 0.0, 0.0, 0.0, 0.0]
    place_surface_offset: 0.0001 # place offset from table

    # Valid distance range when approaching an object for picking
    approach_object_min_dist: 0.0
    approach_object_max_dist: 0.1

    # Valid height range when lifting an object after pick
    lift_object_min_dist: 0.001
    lift_object_max_dist: 0.2
