/**:
  ros__parameters:
    execute: true
    # Total planning attempts
    max_solutions: 10

    # Planning group and link names
    arm_group_name: "arm_0"
    eef_name: "arm_0_eef"
    hand_group_name: "arm_0_gripper"
    hand_frame: "arm_0_end_effector_link"

    # Poses
    hand_open_pose: "open_default"
    hand_close_pose: "close"
    arm_home_pose: "stow"

    # Scene frames
    world_frame: "map"
    table_reference_frame: "base_link"
    object_reference_frame: "arm_0_base_link"
    surface_link: "table"

    # Collision object for picking
    # CYLINDER object specifications
    object_name: "object"
    object_dimensions: [0.04, 0.01] # [height, radius]
    object_pose: [0.0, 0.3, -0.11, 0.0, 0.0, 0.0]

    # Table model
    spawn_table: true
    table_name: "table"
    table_dimensions: [0.1, 0.3, 0.3]  # [length, width, height]
    table_pose: [-0.32, -0.55, 0.19, 0.0, 0.0, 0.0]

    # Gripper grasp frame transform [x,y,z,r,p,y]
    grasp_frame_transform: [0.0, 0.0, 0.14, 1.571, -1.571, 1.571] #[0.0, 0.0, 0.1, 1.571, 0.785, 1.571]

    # Place pose [x,y,z,r,p,y]
    place_pose: [0.6, -0.15, 0.0, 0.0, 0.0, 0.0]
    place_surface_offset: 0.0001 # place offset from table

    # Valid distance range when approaching an object for picking
    approach_object_min_dist: 0.01
    approach_object_max_dist: 0.15

    # Valid height range when lifting an object after pick
    lift_object_min_dist: 0.01
    lift_object_max_dist: 0.1
